### ISSUE TITLE
`torch==1.4.0` does not have `linalg` sub-module

### ISSUE THREAD

**Issue by bonzo-ntu** [NTURobotLearningLab/hprl#3]
When executing `bash run_vae_option_L30.sh` an error occur:  
```
Traceback (most recent call last):
  File "pretrain/trainer_option_new_vae_L30.py", line 29, in <module>  
    from pretrain.SupervisedModel_option_new_vae import SupervisedModel  
  File "./pretrain/SupervisedModel_option_new_vae.py", line 7, in <module>  
    from torch import linalg as LA  
ImportError: cannot import name 'linalg'  
```

`linalg` sub-module is include in pytorch >= 1.7.0, pythorch version in `requirements.txt` should be corrected

**Comment by dannyliu15** [comment]
Fixed with updated `requirement.txt` (torch 1.4 -> torch 1.9.1)
